// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"jan-server/services/mcp-tools/internal/domain/search"
	"jan-server/services/mcp-tools/internal/infrastructure"
	"jan-server/services/mcp-tools/internal/interfaces/httpserver"
	"jan-server/services/mcp-tools/internal/interfaces/httpserver/routes"
	"jan-server/services/mcp-tools/internal/interfaces/httpserver/routes/mcp"
)

import (
	_ "jan-server/services/mcp-tools/internal/infrastructure/metrics"
)

// Injectors from wire.go:

func CreateApplication(ctx context.Context) (*Application, error) {
	config, err := infrastructure.ProvideConfig()
	if err != nil {
		return nil, err
	}
	searchClient := infrastructure.ProvideSearchClient(config)
	searchService := search.NewSearchService(searchClient)
	client := infrastructure.ProvideVectorStoreClient(config)
	serperMCPConfig := routes.ProvideSerperMCPConfig(config)
	serperMCP := mcp.NewSerperMCP(searchService, client, serperMCPConfig)
	mcpproviderConfig := infrastructure.ProvideMCPProviderConfig()
	providerMCP := mcp.NewProviderMCP(mcpproviderConfig)
	sandboxfusionClient := infrastructure.ProvideSandboxFusionClient(config)
	sandboxFusionMCP := routes.ProvideSandboxFusionMCP(sandboxfusionClient, config)
	memoryMCP := routes.ProvideMemoryMCP(config)
	imageGenerateMCP := routes.ProvideImageGenerateMCP(config)
	llmapiClient := infrastructure.ProvideLLMAPIClient(config)
	cache := routes.ProvideToolConfigCache(config, llmapiClient)
	mcpRoute := routes.ProvideMCPRoute(serperMCP, providerMCP, sandboxFusionMCP, memoryMCP, imageGenerateMCP, llmapiClient, cache)
	validator, err := infrastructure.ProvideAuthValidator(ctx, config)
	if err != nil {
		return nil, err
	}
	httpServer := httpserver.NewHTTPServer(config, mcpRoute, validator)
	application := &Application{
		httpServer:  httpServer,
		providerMCP: providerMCP,
	}
	return application, nil
}
