// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"jan-server/services/media-api/internal/config"
	media2 "jan-server/services/media-api/internal/domain/media"
	"jan-server/services/media-api/internal/infrastructure/auth"
	"jan-server/services/media-api/internal/infrastructure/database"
	"jan-server/services/media-api/internal/infrastructure/logger"
	"jan-server/services/media-api/internal/infrastructure/repository/media"
	"jan-server/services/media-api/internal/infrastructure/storage"
	"jan-server/services/media-api/internal/interfaces/httpserver"

	"github.com/google/wire"
	"github.com/rs/zerolog"
	"gorm.io/gorm"
	logger2 "gorm.io/gorm/logger"
)

// Injectors from wire.go:

// BuildApplication assembles the media API with Wire.
func BuildApplication(ctx context.Context) (*Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.New(configConfig)
	databaseConfig := newDatabaseConfig(configConfig)
	db, err := newGormDB(ctx, databaseConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	repository := media.NewRepository(db)
	s3Storage, err := storage.NewS3Storage(ctx, configConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	service := media2.NewService(configConfig, repository, s3Storage, zerologLogger)
	validator, err := auth.NewValidator(ctx, configConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	httpServer := httpserver.New(configConfig, zerologLogger, service, validator)
	application := NewApplication(httpServer, zerologLogger)
	return application, nil
}

// wire.go:

var mediaSet = wire.NewSet(media.NewRepository, wire.Bind(new(media2.Repository), new(*media.Repository)), storage.NewS3Storage, wire.Bind(new(media2.Storage), new(*storage.S3Storage)), media2.NewService)

func newDatabaseConfig(cfg *config.Config) database.Config {
	return database.Config{
		DSN:             cfg.GetDatabaseWriteDSN(),
		MaxIdleConns:    cfg.DBMaxIdleConns,
		MaxOpenConns:    cfg.DBMaxOpenConns,
		ConnMaxLifetime: cfg.DBConnLifetime,
		LogLevel:        logger2.Warn,
	}
}

func newGormDB(ctx context.Context, cfg database.Config, log zerolog.Logger) (*gorm.DB, error) {
	db, err := database.Connect(cfg)
	if err != nil {
		return nil, err
	}
	if err := database.AutoMigrate(ctx, db, log); err != nil {
		return nil, err
	}
	return db, nil
}
