// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package main

import "github.com/janhq/jan-server/services/memory-tools/internal/configs"

// Injectors from wire.go:

func CreateApplication(cfg *configs.Config) (*Application, error) {
	return newApplication(cfg)
}
