// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"jan-server/services/llm-api/internal/domain"
	"jan-server/services/llm-api/internal/domain/apikey"
	"jan-server/services/llm-api/internal/domain/conversation"
	"jan-server/services/llm-api/internal/domain/model"
	"jan-server/services/llm-api/internal/domain/project"
	"jan-server/services/llm-api/internal/domain/user"
	"jan-server/services/llm-api/internal/infrastructure"
	"jan-server/services/llm-api/internal/infrastructure/crontab"
	"jan-server/services/llm-api/internal/infrastructure/database/repository/apikeyrepo"
	"jan-server/services/llm-api/internal/infrastructure/database/repository/conversationrepo"
	"jan-server/services/llm-api/internal/infrastructure/database/repository/modelrepo"
	"jan-server/services/llm-api/internal/infrastructure/database/repository/projectrepo"
	"jan-server/services/llm-api/internal/infrastructure/database/repository/userrepo"
	"jan-server/services/llm-api/internal/infrastructure/inference"
	"jan-server/services/llm-api/internal/infrastructure/logger"
	"jan-server/services/llm-api/internal/interfaces/httpserver"
	"jan-server/services/llm-api/internal/interfaces/httpserver/handlers/apikeyhandler"
	"jan-server/services/llm-api/internal/interfaces/httpserver/handlers/authhandler"
	"jan-server/services/llm-api/internal/interfaces/httpserver/handlers/chathandler"
	"jan-server/services/llm-api/internal/interfaces/httpserver/handlers/conversationhandler"
	guestauth "jan-server/services/llm-api/internal/interfaces/httpserver/handlers/guesthandler"
	"jan-server/services/llm-api/internal/interfaces/httpserver/handlers/modelhandler"
	"jan-server/services/llm-api/internal/interfaces/httpserver/handlers/projecthandler"
	"jan-server/services/llm-api/internal/interfaces/httpserver/routes/auth"
	v1 "jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1"
	"jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1/admin"
	model3 "jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1/admin/model"
	provider2 "jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1/admin/provider"
	"jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1/chat"
	conversation2 "jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1/conversation"
	"jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1/llm/projects"
	model2 "jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1/model"
	"jan-server/services/llm-api/internal/interfaces/httpserver/routes/v1/model/provider"

	_ "net/http/pprof"
)

// Injectors from wire.go:

func CreateApplication() (*Application, error) {
	config, err := infrastructure.ProvideConfig()
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.GetLogger()
	db, err := infrastructure.ProvideDatabase(config, zerologLogger)
	if err != nil {
		return nil, err
	}
	database := infrastructure.ProvideTransactionDatabase(db)
	providerRepository := modelrepo.NewProviderGormRepository(database)
	providerModelRepository := modelrepo.NewProviderModelGormRepository(database)
	modelCatalogRepository := modelrepo.NewModelCatalogGormRepository(database)
	providerModelService := model.NewProviderModelService(providerModelRepository, modelCatalogRepository)
	modelCatalogService := model.NewModelCatalogService(modelCatalogRepository)
	providerService := model.NewProviderService(providerRepository, providerModelService, modelCatalogService)
	modelHandler := modelhandler.NewModelHandler(providerService, providerModelService)
	modelCatalogHandler := modelhandler.NewModelCatalogHandler(modelCatalogService, providerModelService)
	modelProviderRoute := provider.NewModelProviderRoute(modelHandler)
	repository := userrepo.NewUserGormRepository(db)
	service := user.NewService(repository)
	authHandler := authhandler.NewAuthHandler(service, zerologLogger)
	modelRoute := model2.NewModelRoute(modelHandler, modelCatalogHandler, modelProviderRoute, authHandler)
	inferenceProvider := inference.NewInferenceProvider()
	providerHandler := modelhandler.NewProviderHandler(providerService, providerModelService, inferenceProvider)
	conversationRepository := conversationrepo.NewConversationGormRepository(database)
	conversationService := conversation.NewConversationService(conversationRepository)
	projectRepository := projectrepo.NewProjectGormRepository(db)
	projectService := project.NewProjectService(projectRepository)
	conversationHandler := conversationhandler.NewConversationHandler(conversationService, projectService)
	client := infrastructure.ProvideKeycloakClient(config, zerologLogger)
	resolver := infrastructure.ProvideMediaResolver(config, zerologLogger, client)
	chatHandler := chathandler.NewChatHandler(inferenceProvider, providerHandler, conversationHandler, conversationService, resolver)
	chatCompletionRoute := chat.NewChatCompletionRoute(chatHandler, authHandler)
	chatRoute := chat.NewChatRoute(chatCompletionRoute)
	conversationRoute := conversation2.NewConversationRoute(conversationHandler, authHandler)
	projectHandler := projecthandler.NewProjectHandler(projectService)
	projectRoute := projects.NewProjectRoute(projectHandler, authHandler)
	providerModelHandler := modelhandler.NewProviderModelHandler(providerModelService, providerService, modelCatalogService)
	adminModelRoute := model3.NewAdminModelRoute(modelHandler, modelCatalogHandler, providerModelHandler)
	adminProviderRoute := provider2.NewAdminProviderRoute(providerHandler)
	adminRoute := admin.NewAdminRoute(adminModelRoute, adminProviderRoute)
	v1Route := v1.NewV1Route(modelRoute, chatRoute, conversationRoute, projectRoute, adminRoute)
	guestHandler := guestauth.NewGuestHandler(client, zerologLogger)
	upgradeHandler := guestauth.NewUpgradeHandler(client, zerologLogger)
	tokenHandler := authhandler.NewTokenHandler(client, zerologLogger)
	apikeyRepository := apikeyrepo.NewAPIKeyRepository(db)
	apikeyConfig := domain.ProvideAPIKeyConfig(config)
	apikeyService := apikey.NewService(apikeyRepository, repository, client, apikeyConfig, zerologLogger)
	handler := apikeyhandler.NewHandler(apikeyService, zerologLogger)
	keycloakOAuthHandler := authhandler.ProvideKeycloakOAuthHandler(config)
	authRoute := auth.NewAuthRoute(guestHandler, upgradeHandler, tokenHandler, handler, authHandler, keycloakOAuthHandler)
	keycloakValidator, err := infrastructure.ProvideKeycloakValidator(config, zerologLogger)
	if err != nil {
		return nil, err
	}
	infrastructureInfrastructure := infrastructure.NewInfrastructure(db, keycloakValidator, zerologLogger)
	httpServer := httpserver.NewHttpServer(v1Route, authRoute, infrastructureInfrastructure, config)
	crontabCrontab := crontab.NewCrontab(providerService, inferenceProvider)
	application := &Application{
		httpServer: httpServer,
		crontab:    crontabCrontab,
	}
	return application, nil
}

func CreateDataInitializer() (*DataInitializer, error) {
	config, err := infrastructure.ProvideConfig()
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.GetLogger()
	db, err := infrastructure.ProvideDatabase(config, zerologLogger)
	if err != nil {
		return nil, err
	}
	database := infrastructure.ProvideTransactionDatabase(db)
	providerRepository := modelrepo.NewProviderGormRepository(database)
	providerModelRepository := modelrepo.NewProviderModelGormRepository(database)
	modelCatalogRepository := modelrepo.NewModelCatalogGormRepository(database)
	providerModelService := model.NewProviderModelService(providerModelRepository, modelCatalogRepository)
	modelCatalogService := model.NewModelCatalogService(modelCatalogRepository)
	providerService := model.NewProviderService(providerRepository, providerModelService, modelCatalogService)
	inferenceProvider := inference.NewInferenceProvider()
	dataInitializer := &DataInitializer{
		provider:            providerService,
		modelCatalogService: modelCatalogService,
		inferenceProvider:   inferenceProvider,
	}
	return dataInitializer, nil
}
