// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/responses": {
            "post": {
                "description": "Creates a response and orchestrates MCP tool calls when required.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Create a response",
                "parameters": [
                    {
                        "description": "Create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateResponseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponsePayload"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/responses/{response_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Get a response by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Response ID",
                        "name": "response_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponsePayload"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Delete/Cancel a response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Response ID",
                        "name": "response_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponsePayload"
                        }
                    }
                }
            }
        },
        "/v1/responses/{response_id}/cancel": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Cancel a response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Response ID",
                        "name": "response_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponsePayload"
                        }
                    }
                }
            }
        },
        "/v1/responses/{response_id}/input_items": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "List conversation input items",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Response ID",
                        "name": "response_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateResponseRequest": {
            "type": "object",
            "required": [
                "input",
                "model"
            ],
            "properties": {
                "conversation": {
                    "type": "string"
                },
                "input": {},
                "max_tokens": {
                    "type": "integer"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "model": {
                    "type": "string"
                },
                "previous_response_id": {
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                },
                "system_prompt": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "tool_choice": {
                    "$ref": "#/definitions/dto.ToolChoice"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ToolDefinition"
                    }
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "dto.ResponsePayload": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string"
                },
                "created": {
                    "type": "integer"
                },
                "error": {},
                "id": {
                    "type": "string"
                },
                "input": {},
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "output": {},
                "previous_response_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "stream": {
                    "type": "boolean"
                },
                "system_prompt": {
                    "type": "string"
                },
                "usage": {}
            }
        },
        "dto.ToolChoice": {
            "type": "object",
            "properties": {
                "function": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.ToolDefinition": {
            "type": "object",
            "properties": {
                "function": {
                    "$ref": "#/definitions/dto.ToolFunctionDefinition"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.ToolFunctionDefinition": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Response API",
	Description:      "Reference Go microservice skeleton for Jan Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
