// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/rs/zerolog"

	"jan-server/services/realtime-api/internal/config"
	"jan-server/services/realtime-api/internal/domain/session"
	"jan-server/services/realtime-api/internal/infrastructure/auth"
	"jan-server/services/realtime-api/internal/infrastructure/livekit"
	"jan-server/services/realtime-api/internal/infrastructure/store"
	"jan-server/services/realtime-api/internal/interfaces/httpserver"
)

// CreateApplication creates the application with all dependencies wired.
func CreateApplication(
	ctx context.Context,
	cfg *config.Config,
	log zerolog.Logger,
) (*Application, *store.Syncer, error) {
	// Initialize auth validator
	authValidator, err := auth.NewValidator(ctx, cfg, log)
	if err != nil {
		return nil, nil, err
	}

	// Initialize LiveKit clients
	tokenGen := livekit.NewTokenGenerator(cfg)
	roomClient := livekit.NewRoomClient(cfg)

	// Initialize session store
	sessionStore := store.NewMemoryStore(log)

	// Initialize session syncer
	syncer := store.NewSyncer(sessionStore, roomClient, cfg.SessionStaleTTL, cfg.SessionCleanupInterval, log)

	// Initialize session service
	sessionService := session.NewService(
		sessionStore,
		tokenGen,
		cfg.LiveKitWsURL,
		cfg.LiveKitTokenTTL,
		log,
	)

	// Initialize HTTP server
	httpServer := httpserver.New(cfg, log, sessionService, authValidator)

	// Create application
	app := NewApplication(httpServer, syncer, log)

	return app, syncer, nil
}
