// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"jan-server/services/realtime-api/internal/domain"
	"jan-server/services/realtime-api/internal/infrastructure"
	"jan-server/services/realtime-api/internal/interfaces/httpserver"
)

// Injectors from wire.go:

// CreateApplication creates the application with all dependencies wired.
func CreateApplication(ctx context.Context) (*Application, error) {
	config, err := infrastructure.ProvideConfig()
	if err != nil {
		return nil, err
	}
	logger := infrastructure.ProvideLogger(config)
	store := infrastructure.ProvideSessionStore(logger)
	tokenGenerator := infrastructure.ProvideTokenGenerator(config)
	service := domain.ProvideSessionService(store, tokenGenerator, config, logger)
	validator, err := infrastructure.ProvideAuthValidator(ctx, config, logger)
	if err != nil {
		return nil, err
	}
	httpServer := httpserver.New(config, logger, service, validator)
	roomClient := infrastructure.ProvideRoomClient(config)
	syncer := infrastructure.ProvideSyncer(store, roomClient, config, logger)
	application := &Application{
		HTTPServer: httpServer,
		Syncer:     syncer,
		Log:        logger,
		Cfg:        config,
	}
	return application, nil
}
