// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/rs/zerolog"
	"gorm.io/gorm"
	logger2 "gorm.io/gorm/logger"
	"jan-server/services/template-api/internal/config"
	sample2 "jan-server/services/template-api/internal/domain/sample"
	"jan-server/services/template-api/internal/infrastructure/auth"
	"jan-server/services/template-api/internal/infrastructure/database"
	"jan-server/services/template-api/internal/infrastructure/logger"
	"jan-server/services/template-api/internal/infrastructure/repository/sample"
	"jan-server/services/template-api/internal/interfaces/httpserver"
)

// Injectors from wire.go:

// BuildApplication demonstrates how to assemble the template service with Wire.
func BuildApplication(ctx context.Context) (*Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	zerologLogger := logger.New(configConfig)
	databaseConfig := newDatabaseConfig(configConfig)
	db, err := newGormDB(ctx, databaseConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	postgresRepository := sample.NewPostgresRepository(db)
	service := sample2.NewService(postgresRepository, zerologLogger)
	validator, err := newAuthValidator(ctx, configConfig, zerologLogger)
	if err != nil {
		return nil, err
	}
	httpServer := httpserver.New(configConfig, zerologLogger, service, validator)
	application := NewApplication(httpServer, zerologLogger)
	return application, nil
}

// wire.go:

var sampleSet = wire.NewSet(sample.NewPostgresRepository, wire.Bind(new(sample2.Repository), new(*sample.PostgresRepository)), sample2.NewService)

func newDatabaseConfig(cfg *config.Config) database.Config {
	return database.Config{
		DSN:             cfg.DatabaseURL,
		MaxIdleConns:    cfg.DBMaxIdleConns,
		MaxOpenConns:    cfg.DBMaxOpenConns,
		ConnMaxLifetime: cfg.DBConnLifetime,
		LogLevel:        logger2.Warn,
	}
}

func newGormDB(ctx context.Context, cfg database.Config, log zerolog.Logger) (*gorm.DB, error) {
	db, err := database.Connect(cfg)
	if err != nil {
		return nil, err
	}
	if err := database.AutoMigrate(ctx, db, log); err != nil {
		return nil, err
	}
	return db, nil
}

func newAuthValidator(ctx context.Context, cfg *config.Config, log zerolog.Logger) (*auth.Validator, error) {
	return auth.NewValidator(ctx, cfg, log)
}
