// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"jan-server/services/llm-api/internal/infrastructure/database/dbschema"
)

func newConversationItem(db *gorm.DB, opts ...gen.DOOption) conversationItem {
	_conversationItem := conversationItem{}

	_conversationItem.conversationItemDo.UseDB(db, opts...)
	_conversationItem.conversationItemDo.UseModel(&dbschema.ConversationItem{})

	tableName := _conversationItem.conversationItemDo.TableName()
	_conversationItem.ALL = field.NewAsterisk(tableName)
	_conversationItem.ID = field.NewUint(tableName, "id")
	_conversationItem.CreatedAt = field.NewTime(tableName, "created_at")
	_conversationItem.UpdatedAt = field.NewTime(tableName, "updated_at")
	_conversationItem.DeletedAt = field.NewField(tableName, "deleted_at")
	_conversationItem.ConversationID = field.NewUint(tableName, "conversation_id")
	_conversationItem.PublicID = field.NewString(tableName, "public_id")
	_conversationItem.Object = field.NewString(tableName, "object")
	_conversationItem.Branch = field.NewString(tableName, "branch")
	_conversationItem.SequenceNumber = field.NewInt(tableName, "sequence_number")
	_conversationItem.Type = field.NewString(tableName, "type")
	_conversationItem.Role = field.NewString(tableName, "role")
	_conversationItem.Content = field.NewField(tableName, "content")
	_conversationItem.Status = field.NewString(tableName, "status")
	_conversationItem.IncompleteAt = field.NewTime(tableName, "incomplete_at")
	_conversationItem.IncompleteDetails = field.NewField(tableName, "incomplete_details")
	_conversationItem.CompletedAt = field.NewTime(tableName, "completed_at")
	_conversationItem.ResponseID = field.NewUint(tableName, "response_id")
	_conversationItem.Rating = field.NewString(tableName, "rating")
	_conversationItem.RatedAt = field.NewTime(tableName, "rated_at")
	_conversationItem.RatingComment = field.NewString(tableName, "rating_comment")
	_conversationItem.Conversation = conversationItemBelongsToConversation{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Conversation", "dbschema.Conversation"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Conversation.User", "dbschema.User"),
		},
		Items: struct {
			field.RelationField
			Conversation struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Conversation.Items", "dbschema.ConversationItem"),
			Conversation: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Conversation.Items.Conversation", "dbschema.Conversation"),
			},
		},
		Branches: struct {
			field.RelationField
			Conversation struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Conversation.Branches", "dbschema.ConversationBranch"),
			Conversation: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Conversation.Branches.Conversation", "dbschema.Conversation"),
			},
		},
	}

	_conversationItem.fillFieldMap()

	return _conversationItem
}

type conversationItem struct {
	conversationItemDo

	ALL               field.Asterisk
	ID                field.Uint
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field
	ConversationID    field.Uint
	PublicID          field.String
	Object            field.String
	Branch            field.String
	SequenceNumber    field.Int
	Type              field.String
	Role              field.String
	Content           field.Field
	Status            field.String
	IncompleteAt      field.Time
	IncompleteDetails field.Field
	CompletedAt       field.Time
	ResponseID        field.Uint
	Rating            field.String
	RatedAt           field.Time
	RatingComment     field.String
	Conversation      conversationItemBelongsToConversation

	fieldMap map[string]field.Expr
}

func (c conversationItem) Table(newTableName string) *conversationItem {
	c.conversationItemDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c conversationItem) As(alias string) *conversationItem {
	c.conversationItemDo.DO = *(c.conversationItemDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *conversationItem) updateTableName(table string) *conversationItem {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.ConversationID = field.NewUint(table, "conversation_id")
	c.PublicID = field.NewString(table, "public_id")
	c.Object = field.NewString(table, "object")
	c.Branch = field.NewString(table, "branch")
	c.SequenceNumber = field.NewInt(table, "sequence_number")
	c.Type = field.NewString(table, "type")
	c.Role = field.NewString(table, "role")
	c.Content = field.NewField(table, "content")
	c.Status = field.NewString(table, "status")
	c.IncompleteAt = field.NewTime(table, "incomplete_at")
	c.IncompleteDetails = field.NewField(table, "incomplete_details")
	c.CompletedAt = field.NewTime(table, "completed_at")
	c.ResponseID = field.NewUint(table, "response_id")
	c.Rating = field.NewString(table, "rating")
	c.RatedAt = field.NewTime(table, "rated_at")
	c.RatingComment = field.NewString(table, "rating_comment")

	c.fillFieldMap()

	return c
}

func (c *conversationItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *conversationItem) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 21)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["conversation_id"] = c.ConversationID
	c.fieldMap["public_id"] = c.PublicID
	c.fieldMap["object"] = c.Object
	c.fieldMap["branch"] = c.Branch
	c.fieldMap["sequence_number"] = c.SequenceNumber
	c.fieldMap["type"] = c.Type
	c.fieldMap["role"] = c.Role
	c.fieldMap["content"] = c.Content
	c.fieldMap["status"] = c.Status
	c.fieldMap["incomplete_at"] = c.IncompleteAt
	c.fieldMap["incomplete_details"] = c.IncompleteDetails
	c.fieldMap["completed_at"] = c.CompletedAt
	c.fieldMap["response_id"] = c.ResponseID
	c.fieldMap["rating"] = c.Rating
	c.fieldMap["rated_at"] = c.RatedAt
	c.fieldMap["rating_comment"] = c.RatingComment

}

func (c conversationItem) clone(db *gorm.DB) conversationItem {
	c.conversationItemDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Conversation.db = db.Session(&gorm.Session{Initialized: true})
	c.Conversation.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c conversationItem) replaceDB(db *gorm.DB) conversationItem {
	c.conversationItemDo.ReplaceDB(db)
	c.Conversation.db = db.Session(&gorm.Session{})
	return c
}

type conversationItemBelongsToConversation struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
	Items struct {
		field.RelationField
		Conversation struct {
			field.RelationField
		}
	}
	Branches struct {
		field.RelationField
		Conversation struct {
			field.RelationField
		}
	}
}

func (a conversationItemBelongsToConversation) Where(conds ...field.Expr) *conversationItemBelongsToConversation {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a conversationItemBelongsToConversation) WithContext(ctx context.Context) *conversationItemBelongsToConversation {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a conversationItemBelongsToConversation) Session(session *gorm.Session) *conversationItemBelongsToConversation {
	a.db = a.db.Session(session)
	return &a
}

func (a conversationItemBelongsToConversation) Model(m *dbschema.ConversationItem) *conversationItemBelongsToConversationTx {
	return &conversationItemBelongsToConversationTx{a.db.Model(m).Association(a.Name())}
}

func (a conversationItemBelongsToConversation) Unscoped() *conversationItemBelongsToConversation {
	a.db = a.db.Unscoped()
	return &a
}

type conversationItemBelongsToConversationTx struct{ tx *gorm.Association }

func (a conversationItemBelongsToConversationTx) Find() (result *dbschema.Conversation, err error) {
	return result, a.tx.Find(&result)
}

func (a conversationItemBelongsToConversationTx) Append(values ...*dbschema.Conversation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a conversationItemBelongsToConversationTx) Replace(values ...*dbschema.Conversation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a conversationItemBelongsToConversationTx) Delete(values ...*dbschema.Conversation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a conversationItemBelongsToConversationTx) Clear() error {
	return a.tx.Clear()
}

func (a conversationItemBelongsToConversationTx) Count() int64 {
	return a.tx.Count()
}

func (a conversationItemBelongsToConversationTx) Unscoped() *conversationItemBelongsToConversationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type conversationItemDo struct{ gen.DO }

type IConversationItemDo interface {
	gen.SubQuery
	Debug() IConversationItemDo
	WithContext(ctx context.Context) IConversationItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConversationItemDo
	WriteDB() IConversationItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConversationItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConversationItemDo
	Not(conds ...gen.Condition) IConversationItemDo
	Or(conds ...gen.Condition) IConversationItemDo
	Select(conds ...field.Expr) IConversationItemDo
	Where(conds ...gen.Condition) IConversationItemDo
	Order(conds ...field.Expr) IConversationItemDo
	Distinct(cols ...field.Expr) IConversationItemDo
	Omit(cols ...field.Expr) IConversationItemDo
	Join(table schema.Tabler, on ...field.Expr) IConversationItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConversationItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConversationItemDo
	Group(cols ...field.Expr) IConversationItemDo
	Having(conds ...gen.Condition) IConversationItemDo
	Limit(limit int) IConversationItemDo
	Offset(offset int) IConversationItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConversationItemDo
	Unscoped() IConversationItemDo
	Create(values ...*dbschema.ConversationItem) error
	CreateInBatches(values []*dbschema.ConversationItem, batchSize int) error
	Save(values ...*dbschema.ConversationItem) error
	First() (*dbschema.ConversationItem, error)
	Take() (*dbschema.ConversationItem, error)
	Last() (*dbschema.ConversationItem, error)
	Find() ([]*dbschema.ConversationItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.ConversationItem, err error)
	FindInBatches(result *[]*dbschema.ConversationItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbschema.ConversationItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConversationItemDo
	Assign(attrs ...field.AssignExpr) IConversationItemDo
	Joins(fields ...field.RelationField) IConversationItemDo
	Preload(fields ...field.RelationField) IConversationItemDo
	FirstOrInit() (*dbschema.ConversationItem, error)
	FirstOrCreate() (*dbschema.ConversationItem, error)
	FindByPage(offset int, limit int) (result []*dbschema.ConversationItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConversationItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c conversationItemDo) Debug() IConversationItemDo {
	return c.withDO(c.DO.Debug())
}

func (c conversationItemDo) WithContext(ctx context.Context) IConversationItemDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c conversationItemDo) ReadDB() IConversationItemDo {
	return c.Clauses(dbresolver.Read)
}

func (c conversationItemDo) WriteDB() IConversationItemDo {
	return c.Clauses(dbresolver.Write)
}

func (c conversationItemDo) Session(config *gorm.Session) IConversationItemDo {
	return c.withDO(c.DO.Session(config))
}

func (c conversationItemDo) Clauses(conds ...clause.Expression) IConversationItemDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c conversationItemDo) Returning(value interface{}, columns ...string) IConversationItemDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c conversationItemDo) Not(conds ...gen.Condition) IConversationItemDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c conversationItemDo) Or(conds ...gen.Condition) IConversationItemDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c conversationItemDo) Select(conds ...field.Expr) IConversationItemDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c conversationItemDo) Where(conds ...gen.Condition) IConversationItemDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c conversationItemDo) Order(conds ...field.Expr) IConversationItemDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c conversationItemDo) Distinct(cols ...field.Expr) IConversationItemDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c conversationItemDo) Omit(cols ...field.Expr) IConversationItemDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c conversationItemDo) Join(table schema.Tabler, on ...field.Expr) IConversationItemDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c conversationItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConversationItemDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c conversationItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IConversationItemDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c conversationItemDo) Group(cols ...field.Expr) IConversationItemDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c conversationItemDo) Having(conds ...gen.Condition) IConversationItemDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c conversationItemDo) Limit(limit int) IConversationItemDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c conversationItemDo) Offset(offset int) IConversationItemDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c conversationItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConversationItemDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c conversationItemDo) Unscoped() IConversationItemDo {
	return c.withDO(c.DO.Unscoped())
}

func (c conversationItemDo) Create(values ...*dbschema.ConversationItem) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c conversationItemDo) CreateInBatches(values []*dbschema.ConversationItem, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c conversationItemDo) Save(values ...*dbschema.ConversationItem) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c conversationItemDo) First() (*dbschema.ConversationItem, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationItem), nil
	}
}

func (c conversationItemDo) Take() (*dbschema.ConversationItem, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationItem), nil
	}
}

func (c conversationItemDo) Last() (*dbschema.ConversationItem, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationItem), nil
	}
}

func (c conversationItemDo) Find() ([]*dbschema.ConversationItem, error) {
	result, err := c.DO.Find()
	return result.([]*dbschema.ConversationItem), err
}

func (c conversationItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.ConversationItem, err error) {
	buf := make([]*dbschema.ConversationItem, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c conversationItemDo) FindInBatches(result *[]*dbschema.ConversationItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c conversationItemDo) Attrs(attrs ...field.AssignExpr) IConversationItemDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c conversationItemDo) Assign(attrs ...field.AssignExpr) IConversationItemDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c conversationItemDo) Joins(fields ...field.RelationField) IConversationItemDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c conversationItemDo) Preload(fields ...field.RelationField) IConversationItemDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c conversationItemDo) FirstOrInit() (*dbschema.ConversationItem, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationItem), nil
	}
}

func (c conversationItemDo) FirstOrCreate() (*dbschema.ConversationItem, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationItem), nil
	}
}

func (c conversationItemDo) FindByPage(offset int, limit int) (result []*dbschema.ConversationItem, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c conversationItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c conversationItemDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c conversationItemDo) Delete(models ...*dbschema.ConversationItem) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *conversationItemDo) withDO(do gen.Dao) *conversationItemDo {
	c.DO = *do.(*gen.DO)
	return c
}
