// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"jan-server/services/llm-api/internal/infrastructure/database/dbschema"
)

func newConversationBranch(db *gorm.DB, opts ...gen.DOOption) conversationBranch {
	_conversationBranch := conversationBranch{}

	_conversationBranch.conversationBranchDo.UseDB(db, opts...)
	_conversationBranch.conversationBranchDo.UseModel(&dbschema.ConversationBranch{})

	tableName := _conversationBranch.conversationBranchDo.TableName()
	_conversationBranch.ALL = field.NewAsterisk(tableName)
	_conversationBranch.ID = field.NewUint(tableName, "id")
	_conversationBranch.CreatedAt = field.NewTime(tableName, "created_at")
	_conversationBranch.UpdatedAt = field.NewTime(tableName, "updated_at")
	_conversationBranch.DeletedAt = field.NewField(tableName, "deleted_at")
	_conversationBranch.ConversationID = field.NewUint(tableName, "conversation_id")
	_conversationBranch.Name = field.NewString(tableName, "name")
	_conversationBranch.Description = field.NewString(tableName, "description")
	_conversationBranch.ParentBranch = field.NewString(tableName, "parent_branch")
	_conversationBranch.ForkedAt = field.NewTime(tableName, "forked_at")
	_conversationBranch.ForkedFromItemID = field.NewString(tableName, "forked_from_item_id")
	_conversationBranch.ItemCount = field.NewInt(tableName, "item_count")
	_conversationBranch.Conversation = conversationBranchBelongsToConversation{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Conversation", "dbschema.Conversation"),
		User: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Conversation.User", "dbschema.User"),
		},
		Items: struct {
			field.RelationField
			Conversation struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Conversation.Items", "dbschema.ConversationItem"),
			Conversation: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Conversation.Items.Conversation", "dbschema.Conversation"),
			},
		},
		Branches: struct {
			field.RelationField
			Conversation struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Conversation.Branches", "dbschema.ConversationBranch"),
			Conversation: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Conversation.Branches.Conversation", "dbschema.Conversation"),
			},
		},
	}

	_conversationBranch.fillFieldMap()

	return _conversationBranch
}

type conversationBranch struct {
	conversationBranchDo

	ALL              field.Asterisk
	ID               field.Uint
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	ConversationID   field.Uint
	Name             field.String
	Description      field.String
	ParentBranch     field.String
	ForkedAt         field.Time
	ForkedFromItemID field.String
	ItemCount        field.Int
	Conversation     conversationBranchBelongsToConversation

	fieldMap map[string]field.Expr
}

func (c conversationBranch) Table(newTableName string) *conversationBranch {
	c.conversationBranchDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c conversationBranch) As(alias string) *conversationBranch {
	c.conversationBranchDo.DO = *(c.conversationBranchDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *conversationBranch) updateTableName(table string) *conversationBranch {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint(table, "id")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.ConversationID = field.NewUint(table, "conversation_id")
	c.Name = field.NewString(table, "name")
	c.Description = field.NewString(table, "description")
	c.ParentBranch = field.NewString(table, "parent_branch")
	c.ForkedAt = field.NewTime(table, "forked_at")
	c.ForkedFromItemID = field.NewString(table, "forked_from_item_id")
	c.ItemCount = field.NewInt(table, "item_count")

	c.fillFieldMap()

	return c
}

func (c *conversationBranch) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *conversationBranch) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["conversation_id"] = c.ConversationID
	c.fieldMap["name"] = c.Name
	c.fieldMap["description"] = c.Description
	c.fieldMap["parent_branch"] = c.ParentBranch
	c.fieldMap["forked_at"] = c.ForkedAt
	c.fieldMap["forked_from_item_id"] = c.ForkedFromItemID
	c.fieldMap["item_count"] = c.ItemCount

}

func (c conversationBranch) clone(db *gorm.DB) conversationBranch {
	c.conversationBranchDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Conversation.db = db.Session(&gorm.Session{Initialized: true})
	c.Conversation.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c conversationBranch) replaceDB(db *gorm.DB) conversationBranch {
	c.conversationBranchDo.ReplaceDB(db)
	c.Conversation.db = db.Session(&gorm.Session{})
	return c
}

type conversationBranchBelongsToConversation struct {
	db *gorm.DB

	field.RelationField

	User struct {
		field.RelationField
	}
	Items struct {
		field.RelationField
		Conversation struct {
			field.RelationField
		}
	}
	Branches struct {
		field.RelationField
		Conversation struct {
			field.RelationField
		}
	}
}

func (a conversationBranchBelongsToConversation) Where(conds ...field.Expr) *conversationBranchBelongsToConversation {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a conversationBranchBelongsToConversation) WithContext(ctx context.Context) *conversationBranchBelongsToConversation {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a conversationBranchBelongsToConversation) Session(session *gorm.Session) *conversationBranchBelongsToConversation {
	a.db = a.db.Session(session)
	return &a
}

func (a conversationBranchBelongsToConversation) Model(m *dbschema.ConversationBranch) *conversationBranchBelongsToConversationTx {
	return &conversationBranchBelongsToConversationTx{a.db.Model(m).Association(a.Name())}
}

func (a conversationBranchBelongsToConversation) Unscoped() *conversationBranchBelongsToConversation {
	a.db = a.db.Unscoped()
	return &a
}

type conversationBranchBelongsToConversationTx struct{ tx *gorm.Association }

func (a conversationBranchBelongsToConversationTx) Find() (result *dbschema.Conversation, err error) {
	return result, a.tx.Find(&result)
}

func (a conversationBranchBelongsToConversationTx) Append(values ...*dbschema.Conversation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a conversationBranchBelongsToConversationTx) Replace(values ...*dbschema.Conversation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a conversationBranchBelongsToConversationTx) Delete(values ...*dbschema.Conversation) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a conversationBranchBelongsToConversationTx) Clear() error {
	return a.tx.Clear()
}

func (a conversationBranchBelongsToConversationTx) Count() int64 {
	return a.tx.Count()
}

func (a conversationBranchBelongsToConversationTx) Unscoped() *conversationBranchBelongsToConversationTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type conversationBranchDo struct{ gen.DO }

type IConversationBranchDo interface {
	gen.SubQuery
	Debug() IConversationBranchDo
	WithContext(ctx context.Context) IConversationBranchDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConversationBranchDo
	WriteDB() IConversationBranchDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConversationBranchDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConversationBranchDo
	Not(conds ...gen.Condition) IConversationBranchDo
	Or(conds ...gen.Condition) IConversationBranchDo
	Select(conds ...field.Expr) IConversationBranchDo
	Where(conds ...gen.Condition) IConversationBranchDo
	Order(conds ...field.Expr) IConversationBranchDo
	Distinct(cols ...field.Expr) IConversationBranchDo
	Omit(cols ...field.Expr) IConversationBranchDo
	Join(table schema.Tabler, on ...field.Expr) IConversationBranchDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConversationBranchDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConversationBranchDo
	Group(cols ...field.Expr) IConversationBranchDo
	Having(conds ...gen.Condition) IConversationBranchDo
	Limit(limit int) IConversationBranchDo
	Offset(offset int) IConversationBranchDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConversationBranchDo
	Unscoped() IConversationBranchDo
	Create(values ...*dbschema.ConversationBranch) error
	CreateInBatches(values []*dbschema.ConversationBranch, batchSize int) error
	Save(values ...*dbschema.ConversationBranch) error
	First() (*dbschema.ConversationBranch, error)
	Take() (*dbschema.ConversationBranch, error)
	Last() (*dbschema.ConversationBranch, error)
	Find() ([]*dbschema.ConversationBranch, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.ConversationBranch, err error)
	FindInBatches(result *[]*dbschema.ConversationBranch, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbschema.ConversationBranch) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConversationBranchDo
	Assign(attrs ...field.AssignExpr) IConversationBranchDo
	Joins(fields ...field.RelationField) IConversationBranchDo
	Preload(fields ...field.RelationField) IConversationBranchDo
	FirstOrInit() (*dbschema.ConversationBranch, error)
	FirstOrCreate() (*dbschema.ConversationBranch, error)
	FindByPage(offset int, limit int) (result []*dbschema.ConversationBranch, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConversationBranchDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c conversationBranchDo) Debug() IConversationBranchDo {
	return c.withDO(c.DO.Debug())
}

func (c conversationBranchDo) WithContext(ctx context.Context) IConversationBranchDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c conversationBranchDo) ReadDB() IConversationBranchDo {
	return c.Clauses(dbresolver.Read)
}

func (c conversationBranchDo) WriteDB() IConversationBranchDo {
	return c.Clauses(dbresolver.Write)
}

func (c conversationBranchDo) Session(config *gorm.Session) IConversationBranchDo {
	return c.withDO(c.DO.Session(config))
}

func (c conversationBranchDo) Clauses(conds ...clause.Expression) IConversationBranchDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c conversationBranchDo) Returning(value interface{}, columns ...string) IConversationBranchDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c conversationBranchDo) Not(conds ...gen.Condition) IConversationBranchDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c conversationBranchDo) Or(conds ...gen.Condition) IConversationBranchDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c conversationBranchDo) Select(conds ...field.Expr) IConversationBranchDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c conversationBranchDo) Where(conds ...gen.Condition) IConversationBranchDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c conversationBranchDo) Order(conds ...field.Expr) IConversationBranchDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c conversationBranchDo) Distinct(cols ...field.Expr) IConversationBranchDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c conversationBranchDo) Omit(cols ...field.Expr) IConversationBranchDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c conversationBranchDo) Join(table schema.Tabler, on ...field.Expr) IConversationBranchDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c conversationBranchDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConversationBranchDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c conversationBranchDo) RightJoin(table schema.Tabler, on ...field.Expr) IConversationBranchDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c conversationBranchDo) Group(cols ...field.Expr) IConversationBranchDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c conversationBranchDo) Having(conds ...gen.Condition) IConversationBranchDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c conversationBranchDo) Limit(limit int) IConversationBranchDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c conversationBranchDo) Offset(offset int) IConversationBranchDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c conversationBranchDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConversationBranchDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c conversationBranchDo) Unscoped() IConversationBranchDo {
	return c.withDO(c.DO.Unscoped())
}

func (c conversationBranchDo) Create(values ...*dbschema.ConversationBranch) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c conversationBranchDo) CreateInBatches(values []*dbschema.ConversationBranch, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c conversationBranchDo) Save(values ...*dbschema.ConversationBranch) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c conversationBranchDo) First() (*dbschema.ConversationBranch, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationBranch), nil
	}
}

func (c conversationBranchDo) Take() (*dbschema.ConversationBranch, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationBranch), nil
	}
}

func (c conversationBranchDo) Last() (*dbschema.ConversationBranch, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationBranch), nil
	}
}

func (c conversationBranchDo) Find() ([]*dbschema.ConversationBranch, error) {
	result, err := c.DO.Find()
	return result.([]*dbschema.ConversationBranch), err
}

func (c conversationBranchDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.ConversationBranch, err error) {
	buf := make([]*dbschema.ConversationBranch, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c conversationBranchDo) FindInBatches(result *[]*dbschema.ConversationBranch, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c conversationBranchDo) Attrs(attrs ...field.AssignExpr) IConversationBranchDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c conversationBranchDo) Assign(attrs ...field.AssignExpr) IConversationBranchDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c conversationBranchDo) Joins(fields ...field.RelationField) IConversationBranchDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c conversationBranchDo) Preload(fields ...field.RelationField) IConversationBranchDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c conversationBranchDo) FirstOrInit() (*dbschema.ConversationBranch, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationBranch), nil
	}
}

func (c conversationBranchDo) FirstOrCreate() (*dbschema.ConversationBranch, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.ConversationBranch), nil
	}
}

func (c conversationBranchDo) FindByPage(offset int, limit int) (result []*dbschema.ConversationBranch, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c conversationBranchDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c conversationBranchDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c conversationBranchDo) Delete(models ...*dbschema.ConversationBranch) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *conversationBranchDo) withDO(do gen.Dao) *conversationBranchDo {
	c.DO = *do.(*gen.DO)
	return c
}
