// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	Conversation       *conversation
	ConversationBranch *conversationBranch
	ConversationItem   *conversationItem
	Model              *model
	ModelCatalog       *modelCatalog
	Provider           *provider
	ProviderModel      *providerModel
	User               *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Conversation = &Q.Conversation
	ConversationBranch = &Q.ConversationBranch
	ConversationItem = &Q.ConversationItem
	Model = &Q.Model
	ModelCatalog = &Q.ModelCatalog
	Provider = &Q.Provider
	ProviderModel = &Q.ProviderModel
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Conversation:       newConversation(db, opts...),
		ConversationBranch: newConversationBranch(db, opts...),
		ConversationItem:   newConversationItem(db, opts...),
		Model:              newModel(db, opts...),
		ModelCatalog:       newModelCatalog(db, opts...),
		Provider:           newProvider(db, opts...),
		ProviderModel:      newProviderModel(db, opts...),
		User:               newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Conversation       conversation
	ConversationBranch conversationBranch
	ConversationItem   conversationItem
	Model              model
	ModelCatalog       modelCatalog
	Provider           provider
	ProviderModel      providerModel
	User               user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Conversation:       q.Conversation.clone(db),
		ConversationBranch: q.ConversationBranch.clone(db),
		ConversationItem:   q.ConversationItem.clone(db),
		Model:              q.Model.clone(db),
		ModelCatalog:       q.ModelCatalog.clone(db),
		Provider:           q.Provider.clone(db),
		ProviderModel:      q.ProviderModel.clone(db),
		User:               q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Conversation:       q.Conversation.replaceDB(db),
		ConversationBranch: q.ConversationBranch.replaceDB(db),
		ConversationItem:   q.ConversationItem.replaceDB(db),
		Model:              q.Model.replaceDB(db),
		ModelCatalog:       q.ModelCatalog.replaceDB(db),
		Provider:           q.Provider.replaceDB(db),
		ProviderModel:      q.ProviderModel.replaceDB(db),
		User:               q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Conversation       IConversationDo
	ConversationBranch IConversationBranchDo
	ConversationItem   IConversationItemDo
	Model              IModelDo
	ModelCatalog       IModelCatalogDo
	Provider           IProviderDo
	ProviderModel      IProviderModelDo
	User               IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Conversation:       q.Conversation.WithContext(ctx),
		ConversationBranch: q.ConversationBranch.WithContext(ctx),
		ConversationItem:   q.ConversationItem.WithContext(ctx),
		Model:              q.Model.WithContext(ctx),
		ModelCatalog:       q.ModelCatalog.WithContext(ctx),
		Provider:           q.Provider.WithContext(ctx),
		ProviderModel:      q.ProviderModel.WithContext(ctx),
		User:               q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
