// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gormgen

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"jan-server/services/llm-api/internal/infrastructure/database/dbschema"
)

func newUserSettings(db *gorm.DB, opts ...gen.DOOption) userSettings {
	_userSettings := userSettings{}

	_userSettings.userSettingsDo.UseDB(db, opts...)
	_userSettings.userSettingsDo.UseModel(&dbschema.UserSettings{})

	tableName := _userSettings.userSettingsDo.TableName()
	_userSettings.ALL = field.NewAsterisk(tableName)
	_userSettings.ID = field.NewUint(tableName, "id")
	_userSettings.UserID = field.NewUint(tableName, "user_id")
	_userSettings.EnableTrace = field.NewBool(tableName, "enable_trace")
	_userSettings.EnableTools = field.NewBool(tableName, "enable_tools")
	_userSettings.MemoryConfig = field.NewField(tableName, "memory_config")
	_userSettings.ProfileSettings = field.NewField(tableName, "profile_settings")
	_userSettings.AdvancedSettings = field.NewField(tableName, "advanced_settings")
	_userSettings.Preferences = field.NewField(tableName, "preferences")
	_userSettings.CreatedAt = field.NewTime(tableName, "created_at")
	_userSettings.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userSettings.fillFieldMap()

	return _userSettings
}

type userSettings struct {
	userSettingsDo

	ALL              field.Asterisk
	ID               field.Uint
	UserID           field.Uint
	EnableTrace      field.Bool
	EnableTools      field.Bool
	MemoryConfig     field.Field
	ProfileSettings  field.Field
	AdvancedSettings field.Field
	Preferences      field.Field
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (u userSettings) Table(newTableName string) *userSettings {
	u.userSettingsDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userSettings) As(alias string) *userSettings {
	u.userSettingsDo.DO = *(u.userSettingsDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userSettings) updateTableName(table string) *userSettings {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.UserID = field.NewUint(table, "user_id")
	u.EnableTrace = field.NewBool(table, "enable_trace")
	u.EnableTools = field.NewBool(table, "enable_tools")
	u.MemoryConfig = field.NewField(table, "memory_config")
	u.ProfileSettings = field.NewField(table, "profile_settings")
	u.AdvancedSettings = field.NewField(table, "advanced_settings")
	u.Preferences = field.NewField(table, "preferences")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userSettings) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userSettings) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 10)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["enable_trace"] = u.EnableTrace
	u.fieldMap["enable_tools"] = u.EnableTools
	u.fieldMap["memory_config"] = u.MemoryConfig
	u.fieldMap["profile_settings"] = u.ProfileSettings
	u.fieldMap["advanced_settings"] = u.AdvancedSettings
	u.fieldMap["preferences"] = u.Preferences
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userSettings) clone(db *gorm.DB) userSettings {
	u.userSettingsDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userSettings) replaceDB(db *gorm.DB) userSettings {
	u.userSettingsDo.ReplaceDB(db)
	return u
}

type userSettingsDo struct{ gen.DO }

type IUserSettingsDo interface {
	gen.SubQuery
	Debug() IUserSettingsDo
	WithContext(ctx context.Context) IUserSettingsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserSettingsDo
	WriteDB() IUserSettingsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserSettingsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserSettingsDo
	Not(conds ...gen.Condition) IUserSettingsDo
	Or(conds ...gen.Condition) IUserSettingsDo
	Select(conds ...field.Expr) IUserSettingsDo
	Where(conds ...gen.Condition) IUserSettingsDo
	Order(conds ...field.Expr) IUserSettingsDo
	Distinct(cols ...field.Expr) IUserSettingsDo
	Omit(cols ...field.Expr) IUserSettingsDo
	Join(table schema.Tabler, on ...field.Expr) IUserSettingsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserSettingsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserSettingsDo
	Group(cols ...field.Expr) IUserSettingsDo
	Having(conds ...gen.Condition) IUserSettingsDo
	Limit(limit int) IUserSettingsDo
	Offset(offset int) IUserSettingsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserSettingsDo
	Unscoped() IUserSettingsDo
	Create(values ...*dbschema.UserSettings) error
	CreateInBatches(values []*dbschema.UserSettings, batchSize int) error
	Save(values ...*dbschema.UserSettings) error
	First() (*dbschema.UserSettings, error)
	Take() (*dbschema.UserSettings, error)
	Last() (*dbschema.UserSettings, error)
	Find() ([]*dbschema.UserSettings, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.UserSettings, err error)
	FindInBatches(result *[]*dbschema.UserSettings, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbschema.UserSettings) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserSettingsDo
	Assign(attrs ...field.AssignExpr) IUserSettingsDo
	Joins(fields ...field.RelationField) IUserSettingsDo
	Preload(fields ...field.RelationField) IUserSettingsDo
	FirstOrInit() (*dbschema.UserSettings, error)
	FirstOrCreate() (*dbschema.UserSettings, error)
	FindByPage(offset int, limit int) (result []*dbschema.UserSettings, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserSettingsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userSettingsDo) Debug() IUserSettingsDo {
	return u.withDO(u.DO.Debug())
}

func (u userSettingsDo) WithContext(ctx context.Context) IUserSettingsDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userSettingsDo) ReadDB() IUserSettingsDo {
	return u.Clauses(dbresolver.Read)
}

func (u userSettingsDo) WriteDB() IUserSettingsDo {
	return u.Clauses(dbresolver.Write)
}

func (u userSettingsDo) Session(config *gorm.Session) IUserSettingsDo {
	return u.withDO(u.DO.Session(config))
}

func (u userSettingsDo) Clauses(conds ...clause.Expression) IUserSettingsDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userSettingsDo) Returning(value interface{}, columns ...string) IUserSettingsDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userSettingsDo) Not(conds ...gen.Condition) IUserSettingsDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userSettingsDo) Or(conds ...gen.Condition) IUserSettingsDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userSettingsDo) Select(conds ...field.Expr) IUserSettingsDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userSettingsDo) Where(conds ...gen.Condition) IUserSettingsDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userSettingsDo) Order(conds ...field.Expr) IUserSettingsDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userSettingsDo) Distinct(cols ...field.Expr) IUserSettingsDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userSettingsDo) Omit(cols ...field.Expr) IUserSettingsDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userSettingsDo) Join(table schema.Tabler, on ...field.Expr) IUserSettingsDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userSettingsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserSettingsDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userSettingsDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserSettingsDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userSettingsDo) Group(cols ...field.Expr) IUserSettingsDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userSettingsDo) Having(conds ...gen.Condition) IUserSettingsDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userSettingsDo) Limit(limit int) IUserSettingsDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userSettingsDo) Offset(offset int) IUserSettingsDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userSettingsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserSettingsDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userSettingsDo) Unscoped() IUserSettingsDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userSettingsDo) Create(values ...*dbschema.UserSettings) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userSettingsDo) CreateInBatches(values []*dbschema.UserSettings, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userSettingsDo) Save(values ...*dbschema.UserSettings) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userSettingsDo) First() (*dbschema.UserSettings, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.UserSettings), nil
	}
}

func (u userSettingsDo) Take() (*dbschema.UserSettings, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.UserSettings), nil
	}
}

func (u userSettingsDo) Last() (*dbschema.UserSettings, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.UserSettings), nil
	}
}

func (u userSettingsDo) Find() ([]*dbschema.UserSettings, error) {
	result, err := u.DO.Find()
	return result.([]*dbschema.UserSettings), err
}

func (u userSettingsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbschema.UserSettings, err error) {
	buf := make([]*dbschema.UserSettings, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userSettingsDo) FindInBatches(result *[]*dbschema.UserSettings, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userSettingsDo) Attrs(attrs ...field.AssignExpr) IUserSettingsDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userSettingsDo) Assign(attrs ...field.AssignExpr) IUserSettingsDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userSettingsDo) Joins(fields ...field.RelationField) IUserSettingsDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userSettingsDo) Preload(fields ...field.RelationField) IUserSettingsDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userSettingsDo) FirstOrInit() (*dbschema.UserSettings, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.UserSettings), nil
	}
}

func (u userSettingsDo) FirstOrCreate() (*dbschema.UserSettings, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbschema.UserSettings), nil
	}
}

func (u userSettingsDo) FindByPage(offset int, limit int) (result []*dbschema.UserSettings, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userSettingsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userSettingsDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userSettingsDo) Delete(models ...*dbschema.UserSettings) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userSettingsDo) withDO(do gen.Dao) *userSettingsDo {
	u.DO = *do.(*gen.DO)
	return u
}
